apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: test-app
metadata:
  name: Hello-World App
  description: Hello World App
  version: "0.2.4-requiredResources"
  catalog:
    organization:
      - name: Weidmüller Development
        site: weidmueller.com
deploymentProfiles:
  - type: compose
    id: hello-world-app
    requiredResources:
        - cpu:
            - cores: 3.0
    components:
      - name: hello-world-app
        properties:
          packageLocation: https://margo2.germanywestcentral.cloudapp.azure.com:3000/margo/hello-world-FLECS-app/raw/branch/main/manifest.json
parameters:
  UI:
    value: 3000
    targets:
      - pointer: PORTS.3000
        components: ["hello-world-app"]
