apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
metadata:
  id: test-app
  name: Hello-World App
  description: Hello World App
  version: "0.1.6"
  catalog:
    application:
      icon: /compose-org.test.app/resources/logo.png
      tagline: Schnelle App zum Testen der Pipeline
      descriptionFile: ./resources/description.md
      tags: ["test","hello","world"]
    organization:
      - name: Weidmüller Development
        site: weidmueller.com
deploymentProfiles:
  - type: compose
    id: hello-world-app
    components:
      - name: hello-world-app
        properties:
          packageLocation: https://ghcr.io/lw01194-wi/container/library/hello-world-app-lw:latest
parameters:
  UI:
    value: 3000
    targets:
      - pointer: PORTS.3000
        components: ["hello-world-app"]
