apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: demo-app
metadata:
  name: Hello-World DEMO App
  description: Hello World App
  version: "0.4-0"
  catalog:
    organization:
      - name: Weidmüller Development
        site: weidmueller.com
deploymentProfiles:
  - type: compose
    id: demo-app
    components:
      - name: demo-app
        properties:
          packageLocation: https://margo2.germanywestcentral.cloudapp.azure.com:3000/margo/hello-world-FLECS-app/raw/commit/e38ec6db9a07aa693accbffc9ae4334d3618db97/manifest.json
parameters:
  UI:
    value: 3000
    targets:
      - pointer: PORTS.3000
        components: ["demo-app"]
