apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: demo-app
metadata:
  name: Hello-World DEMO App
  description: Hello World App
  version: "0.3-0"
  catalog:
    organization:
      - name: Weidmüller Development
        site: weidmueller.com
deploymentProfiles:
  - type: compose
    id: demo-app
    components:
      - name: demo-app
        properties:
          packageLocation: https://margo2.germanywestcentral.cloudapp.azure.com:3000/margo/hello-world-FLECS-app/raw/commit/e23d7d75dad565037213d12e2348658e9e20b6be/manifest.json
parameters:
  UI:
    value: 3000
    targets:
      - pointer: PORTS.3000
        components: ["demo-app"]
