apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
id: demo-app
metadata:
  name: Hello-World DEMO App
  description: Hello World App
  version: "1.0"
  catalog:
    organization:
      - name: Weidmüller Development
        site: weidmueller.com
deploymentProfiles:
  - type: compose
    id: demo-app
    components:
      - name: demo-app
        properties:
          packageLocation: https://margo2.germanywestcentral.cloudapp.azure.com:3000/margo/hello-world-FLECS-app/raw/commit/b2b930de390712d74f6950dbe2165d7f61a7bb6e/manifest.json
parameters:
  demo-param:
    value: false
    targets:
      - pointer: featureFlag
        components: ["demo-app"]
